spring.application.name=ecommerce

# Configurações do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/nexus_gaming_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Configurações do Hibernate / JPA
# O 'update' cria ou atualiza as tabelas automaticamente com base no seu código Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# RNF0013 - script de implantacao que popula as tabelas de dominio (ex: bandeiras de cartao)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
